name: Send WhatsApp message to rotating person

on:
  schedule:
    # 14:00 UTC = 09:00 Bogotá (ajusta si quieres)
    - cron: '0 14 * * 1-5'   # de lunes a viernes
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    env:
      WA_TOKEN: ${{ secrets.WA_TOKEN }}
      WA_PHONE_NUMBER_ID: ${{ secrets.WA_PHONE_NUMBER_ID }}
    steps:
      - name: Pick person by weekday
        id: pick
        run: |
          # Día de la semana (1=lunes ... 7=domingo)
          DOW=$(date -u +%u)
          case $DOW in
            1) PHONE=${{ secrets.WA_PHONE_A }}; NAME=${{ secrets.WA_NAME_A }} ;;
            2) PHONE=${{ secrets.WA_PHONE_B }}; NAME=${{ secrets.WA_NAME_B }} ;;
            3) PHONE=${{ secrets.WA_PHONE_C }}; NAME=${{ secrets.WA_NAME_C }} ;;
            4) PHONE=${{ secrets.WA_PHONE_A }}; NAME=${{ secrets.WA_NAME_A }} ;;
            5) PHONE=${{ secrets.WA_PHONE_B }}; NAME=${{ secrets.WA_NAME_B }} ;;
            *) PHONE=${{ secrets.WA_PHONE_C }}; NAME=${{ secrets.WA_NAME_C }} ;;
          esac
          echo "phone=$PHONE" >> $GITHUB_OUTPUT
          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "text=Tu tarea de hoy es revisar el riego 🚿🌱" >> $GITHUB_OUTPUT

      - name: Send template message
        run: |
          curl -sS -X POST "https://graph.facebook.com/v20.0/${WA_PHONE_NUMBER_ID}/messages" \
            -H "Authorization: Bearer ${WA_TOKEN}" \
            -H "Content-Type: application/json" \
            -d "{
              \"messaging_product\": \"whatsapp\",
              \"to\": \"${{ steps.pick.outputs.phone }}\",
              \"type\": \"template\",
              \"template\": {
                \"name\": \"daily_tip_v1\",
                \"language\": { \"code\": \"es\" },
                \"components\": [
                  { \"type\": \"body\", \"parameters\": [
                    { \"type\": \"text\", \"text\": \"${{ steps.pick.outputs.name }}\" },
                    { \"type\": \"text\", \"text\": \"${{ steps.pick.outputs.text }}\" }
                  ]}
                ]
              }
            }" | jq .
